version: '2'
services:
  redis-cluster:
    environment:
     IP: ${REDIS_CLUSTER_IP}
     SENTINEL: ${REDIS_USE_SENTINEL}
     STANDALONE: ${REDIS_USE_STANDALONE}
    build:
      context: .
      args:
        redis_version: '5.0.4'
    hostname: server
    ports:
      - '17000-17007:17000-17007'
      - '5000-5002:5000-5002'
